# Generated by Django 3.2.7 on 2021-09-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210918_1124'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(db_index=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='book.book')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='range',
        ),
        migrations.AddField(
            model_name='comment',
            name='first_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='last_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Range',
        ),
        migrations.AddField(
            model_name='comment',
            name='scopes',
            field=models.ManyToManyField(related_name='comments', to='post.Scope'),
        ),
    ]
